plugins {
    id "com.android.application"
}

android {
    namespace "com.streamlite.player"
    compileSdk 35

    defaultConfig {
        applicationId "com.streamlite.player"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    def media3Version = "1.4.1"
    implementation "androidx.media3:media3-exoplayer:$media3Version"
    implementation "androidx.media3:media3-datasource-rtmp:$media3Version"
    implementation "androidx.media3:media3-ui:$media3Version"
}
